import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {NuqsAdapter} from 'nuqs/adapters/next'
import { TRPCReactProvider } from "@/trpc/client";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/context/theme-context";

const inter = Inter({
 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
    <TRPCReactProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className,"theme-transition"}  antialiased`}
      >
        <Toaster/>
        <ThemeProvider>
        {children}
        </ThemeProvider>
      </body>
    </html>
  </TRPCReactProvider>
  </NuqsAdapter>
  );
}
